/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SideNavbar from "@/components/SideNavbar";
import ReduxProvider from "@/store/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });
import 'react-phone-input-2/lib/style.css'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg- bg-[#E3EBF8] text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        {/* sidebar */}
        {/* <p className="border">Sidebar</p> */}
        {/* main page */}
        <SideNavbar />
        <ReduxProvider>
          <div className="p-8 w-full">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
